export enum FoodCategory {
  VEGETABLES = "Vegetables",
  FRUITS = "Fruits",
  DAIRY = "Dairy",
  MEAT = "Meat",
  SEAFOOD = "Seafood",
  GRAINS = "Grains",
  LEGUMES = "Legumes",
  NUTS_AND_SEEDS = "Nuts and Seeds",
  HERBS_AND_SPICES = "Herbs and Spices",
  OILS_AND_FATS = "Oils and Fats",
  BEVERAGES = "Beverages",
  SWEETS_AND_CONFECTIONS = "Sweets and Confections",
  BAKED_GOODS = "Baked Goods",
  CONDIMENTS_AND_SAUCES = "Condiments and Sauces",
  FERMENTED_FOODS = "Fermented Foods",
  PROCESSED_FOODS = "Processed Foods",
  CEREALS = "Cereals",
  PASTA_AND_NOODLES = "Pasta and Noodles",
  SOUPS_AND_STEWS = "Soups and Stews",
  FROZEN_FOODS = "Frozen Foods",
  CANNED_GOODS = "Canned Goods",
  SNACKS = "Snacks",
  EGGS = "Eggs",
  POULTRY = "Poultry",
  ALTERNATIVE_PROTEINS = "Alternative Proteins",
}
